Repository ai-surfers/pocket-prompt-frontend, pull requests merged in 2024-10, with the labels that each got.

#11 [기타] Cloudflare 배포룰 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/preview.yml
  .gitmodules
  .nvmrc
  index.html
  package.json
  src/components/Header/Header.tsx
  src/components/extension/PocketPromptPage.tsx
  src/pages/extension/ExtensionPage.tsx
  src/pages/home/HomePage.tsx
  src/router/Router.tsx
Labels: ⚙️ chore

#16 2024.10.16
  public/svg/logo.svg
  public/svg/logo_primary.svg
  src/.prettierrc
  src/assets/images/extension/background-textures.png
  src/assets/images/extension/claude-icon.png
  src/assets/images/extension/demo-image.png
  src/assets/images/extension/gemini-icon.png
  src/assets/images/extension/gpt-icon.png
  src/assets/images/extension/pocket-prompt-demo-video.gif
  src/assets/images/extension/prompt-usage-demo.png
  src/assets/images/extension/speech-balloon-prompt.png
  src/assets/images/logo-white.png
  src/assets/svg/Logo.tsx
  src/assets/svg/LogoPrimary.tsx
  src/assets/svg/extension/ArrowUpRight.tsx
  src/assets/svg/extension/CheckBox.tsx
  src/assets/svg/index.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/components/Header/Header.tsx
  src/components/Header/LoginButton/LoginButton.tsx
  src/components/Header/User/User.tsx
  src/components/extension/PocketPromptPage.tsx
  src/components/price/Footer.tsx
  src/components/price/Plan/Plan.tsx
  src/index.css
  src/layouts/Layout.tsx
  src/pages/extension/ExtensionPage.tsx
  src/pages/extension/components/Extension1/index.tsx
  src/pages/extension/components/Extension1/styles.ts
  src/pages/extension/components/Extension2/index.tsx
  src/pages/extension/components/Extension2/styles.ts
  src/pages/extension/components/Extension3/index.tsx
  src/pages/extension/components/Extension3/styles.ts
  src/pages/extension/components/Extension4/index.tsx
  src/pages/extension/components/Extension4/styles.ts
  src/pages/extension/components/Extension5/index.tsx
  src/pages/extension/components/Extension5/styles.ts
  src/pages/extension/index.tsx
  src/pages/extension/styles.ts
  src/pages/home/index.tsx
  src/pages/my/index.tsx
  src/pages/price/components/Explain.tsx
  src/pages/price/components/FAQ.tsx
  src/pages/price/components/Footer.tsx
  src/pages/price/components/Plan/Plan.tsx
  src/pages/price/components/Plan/PlanCard.tsx
  src/pages/price/components/Plan/PlanData.ts
  src/pages/price/index.tsx
  src/router/Router.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🎯merge

#18 [익스텐션 페이지] 퍼블리싱
  index.html
  package.json
  src/assets/images/extension/extension7-background-image.png
  src/assets/images/extension/mouse-image.png
  src/assets/images/extension/user/user-1.png
  src/assets/images/extension/user/user-2.png
  src/assets/images/extension/user/user-3.png
  src/assets/images/extension/user/user-4.png
  src/assets/images/extension/user/user-5.png
  src/assets/images/extension/user/user-6.png
  src/assets/images/extension/user/user-7.png
  src/assets/svg/extension/arrow-down.svg
  src/assets/svg/extension/arrow-up.svg
  src/assets/svg/extension/extension8-icon1.svg
  src/assets/svg/extension/extension8-icon2.svg
  src/assets/svg/extension/extension8-icon3.svg
  src/assets/svg/extension/logo.svg
  src/assets/svg/extension/video-band-half.svg
  src/assets/svg/extension/video-band.svg
  src/assets/svg/extension/video-star.svg
  src/pages/extension/components/Extension1/index.tsx
  src/pages/extension/components/Extension1/styles.ts
  src/pages/extension/components/Extension4/index.tsx
  src/pages/extension/components/Extension4/styles.ts
  src/pages/extension/components/Extension5/index.tsx
  src/pages/extension/components/Extension5/styles.ts
  src/pages/extension/components/Extension6/carouselData.ts
  src/pages/extension/components/Extension6/index.tsx
  src/pages/extension/components/Extension6/styles.ts
  src/pages/extension/components/Extension7/index.tsx
  src/pages/extension/components/Extension7/styles.ts
  src/pages/extension/components/Extension8/index.tsx
  src/pages/extension/components/Extension8/styles.ts
  src/pages/extension/components/Extension9/QnAToggle.tsx
  src/pages/extension/components/Extension9/index.tsx
  src/pages/extension/components/Extension9/qnaData.tsx
  src/pages/extension/components/Extension9/styles.ts
  src/pages/extension/components/styles.ts
  src/pages/extension/index.tsx
  yarn.lock
Labels: ✨ feat
